### PR TITLE
Clear flag support in multi-progress

### PR DESCRIPTION
**Pull request by Confuseh**
Found this project today, but when tried using - found out that clear flag doesn't matter with multi-progress, so I forked and made some changes

Whether it will appear on multi-progress itself, you decide :)

~ confuseh

### CODE REVIEW

**Comment by Confuseh** [comment]
Scratch that. Tested a bit more and it's real unstable. For something like 1 static multi-progress and a lot of smaller multi-progresses that disappear - this is perfect, for something more complex it messes up big time.

Maybe allow it as under certain flag or whatever..

**Comment by Confuseh** [comment]
Well now it feels bit more stable, I tried a lot of different scenario's and it surely worked fine, but I believe if I would log something after each and every progress - it would get crazy and buggy, but if to log after all of them are complete aka checking if multi.complete == true it wouldn't get any crazy or anything like that.

**Comment by FlomoN** [comment]
pls merge, works flawless :)

**Comment by Confuseh** [comment]
lol its been 4 years i highly doubt anyone cares at this point, not even I do.

**Comment by pitaj** [comment]
I was actually going to merge this when I had a chance. I completely forgot about this repo until his gentle reminder today.

**Pull request closed without merging**
